import React from "react";
import SelectSearchable from "./select/selectSearchable";
import { ItemBaseType } from "./select/searchableList";
import ReactDOM from "react-dom";

export const items: Array<ItemBaseType> = [
  { label: "Forró", value: "forro" },
  { label: "Sertanejo", value: "sertanejo" },
  { label: "Funk", value: "funk" },
  { label: "Brega Funk", value: "brega-funk" },
  { label: "Arrocha", value: "arrocha" },
  { label: "Brega", value: "brega" },
  { label: "Romântico", value: "romantico" },
  { label: "Reggae", value: "reggae" },
  { label: "Pop", value: "pop" },
  { label: "Regional", value: "regional" },
  { label: "Eletrônica", value: "eletronica" },
  { label: "Swingueira", value: "swingueira" },
  { label: "Bregadeira", value: "bregadeira" },
  { label: "Samba", value: "samba" },
  { label: "Católica", value: "catolica" },
  { label: "MPB", value: "mpb" },
  { label: "Rock", value: "rock" },
  { label: "Pop Rock", value: "pop-rock" },
  { label: "Folk", value: "folk" },
  { label: "Reggaeton", value: "reggaeton" },
  { label: "Paródia / Comédia", value: "parodiacomedia" },
  { label: "Infantil", value: "infantil" },
  { label: "House", value: "house" },
  { label: "World Music", value: "world-music" },
  { label: "Alternativo", value: "alternativo" },
  { label: "Country", value: "country" },
  { label: "Tecnobrega", value: "tecnobrega" },
  { label: "Instrumental", value: "instrumental" },
  { label: "Trance", value: "trance" },
  { label: "Indie", value: "indie" },
  { label: "Black Music", value: "black-music" },
  { label: "Hardcore", value: "hardcore" },
  { label: "Heavy Metal", value: "heavy-metal" },
  { label: "Experimental", value: "experimental" },
  { label: "R&B", value: "reb" },
  { label: "Punk Rock", value: "punk-rock" },
  { label: "Blues", value: "blues" },
  { label: "Surf Music", value: "surf-music" },
  { label: "Bossa Nova", value: "bossa-nova" },
  { label: "Jazz", value: "jazz" },
  { label: "Samba Rock", value: "samba-rock" },
  { label: "Soul", value: "soul" },
  { label: "Hard Rock", value: "hard-rock" },
  { label: "Instrumental Brasileiro", value: "instrumental-brasileiro" },
  { label: "Rock Progressivo", value: "rock-progressivo" },
  { label: "Gótico", value: "gotico" },
  { label: "Death Metal", value: "death-metal" },
  { label: "Choro", value: "choro" },
  { label: "Erudito", value: "erudito" },
  { label: "Industrial", value: "industrial" },
  { label: "Guitar", value: "guitar" },
  { label: "Emocore", value: "emocore" },
  { label: "New Metal", value: "new-metal" },
  { label: "Metal Melódico", value: "metal-melodico" },
  { label: "Grunge", value: "grunge" },
  { label: "Thrash Metal", value: "thrash-metal" },
  { label: "New Age", value: "new-age" },
];

ReactDOM.render(
  <SelectSearchable items={items} onSelectedItem={() => {}} hasSearch={true} />,
  document.body
);
